### ISSUE TITLE
prototipo 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/practicaprototipos-turbandaxd#2]
[prototipo.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-turbandaxd/files/6203553/prototipo.pdf)

**Comment by Eva155** [comment]
Calificación: 18 puntos
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
