### ISSUE TITLE
Reporte de la Calculadora 

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/practicaprototipos-turbandaxd#3]
[Reporte de Calculadora.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-turbandaxd/files/6203748/Reporte.de.Calculadora.pdf)

**Comment by Eva155** [comment]
Muy buena explicación del procedimiento.
Calificación: 19 puntos
Calificó:Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
